// <auto-generated />
using System;
using Kiosk.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiosk.Infrastructure.Migrations
{
    [DbContext(typeof(KioskContext))]
    partial class KioskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kiosk.Domain.Models.CartItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CartId")
                        .HasColumnType("char(36)")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_id");

                    b.Property<decimal>("SnapShotPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("snapshot_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("cart_item_id");

                    b.HasIndex("CartId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("VariantId");

                    b.ToTable("tb_cart_item", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CartModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("client");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("session_token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("cart_id");

                    b.ToTable("tb_cart", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CodeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("code_id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("tb_code", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CombinationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CombId")
                        .HasColumnType("char(36)")
                        .HasColumnName("comb_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("PartId")
                        .HasColumnType("char(36)")
                        .HasColumnName("part_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("combination_id");

                    b.HasIndex("CombId");

                    b.HasIndex("PartId");

                    b.ToTable("tb_combination", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.IngredientModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("available");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("ingredient_id");

                    b.HasIndex("ServiceId");

                    b.ToTable("tb_ingredient", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CartId")
                        .HasColumnType("char(36)")
                        .HasColumnName("cart_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("index");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("order_id");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("tb_order", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.OrganizationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("organization_id");

                    b.ToTable("tb_organization", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryIngredientModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("price_history_ingredient_id");

                    b.HasIndex("IngredientId");

                    b.ToTable("tb_price_history_ingredient", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryVariantModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("price_history_variant_id");

                    b.HasIndex("VariantId");

                    b.ToTable("tb_price_history_variant", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.ServiceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("available");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("service_id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("tb_service", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.VariantIngredientModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("available");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("variant_ingredient_id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("VariantId");

                    b.ToTable("tb_variant_ingredient", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.VariantModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("available");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Ingredients")
                        .HasColumnType("int")
                        .HasColumnName("ingredients");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("service_id");

                    b.Property<bool>("Surpass")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("surpass");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("variant_id");

                    b.HasIndex("ServiceId");

                    b.ToTable("tb_variant", (string)null);
                });

            modelBuilder.Entity("tb_cart_item_ingredient", b =>
                {
                    b.Property<Guid>("CartItemsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.HasKey("CartItemsId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("tb_cart_item_ingredient");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CartItemModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.CartModel", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.CartItemModel", "Reference")
                        .WithMany("CartItems")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.VariantModel", "Variant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Reference");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CodeModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.OrganizationModel", "Organization")
                        .WithMany("Codes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CombinationModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.VariantModel", "Comb")
                        .WithMany("Parts")
                        .HasForeignKey("CombId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.VariantModel", "Part")
                        .WithMany("Combs")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comb");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.IngredientModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.ServiceModel", "Service")
                        .WithMany("Ingredients")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.OrderModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.CartModel", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("Kiosk.Domain.Models.OrderModel", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryIngredientModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.IngredientModel", "Ingredient")
                        .WithMany("PriceHistoryIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryVariantModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.VariantModel", "Variant")
                        .WithMany("PriceHistoryVariants")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.ServiceModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.OrganizationModel", "Organization")
                        .WithMany("Services")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.VariantIngredientModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.IngredientModel", "Ingredient")
                        .WithMany("VariantIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.VariantModel", "Variant")
                        .WithMany("VariantIngredients")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.VariantModel", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.ServiceModel", "Service")
                        .WithMany("Variants")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("tb_cart_item_ingredient", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.CartItemModel", null)
                        .WithMany()
                        .HasForeignKey("CartItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.IngredientModel", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CartItemModel", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CartModel", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.IngredientModel", b =>
                {
                    b.Navigation("PriceHistoryIngredients");

                    b.Navigation("VariantIngredients");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.OrganizationModel", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.ServiceModel", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.VariantModel", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Combs");

                    b.Navigation("Parts");

                    b.Navigation("PriceHistoryVariants");

                    b.Navigation("VariantIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
