// <auto-generated />
using System;
using Kiosk.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiosk.Persistence.Migrations
{
    [DbContext(typeof(KioskContext))]
    [Migration("20260308203601_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CartItemIngredient", b =>
                {
                    b.Property<Guid>("CartItemsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CartItemsId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("CartItemIngredient");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("cart_id");

                    b.ToTable("tb_cart", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SnapShotPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("cartitem_id");

                    b.HasIndex("CartId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("VariantId");

                    b.ToTable("tb_cartitem", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Combination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CombId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("PartId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("combination_id");

                    b.HasIndex("CombId");

                    b.HasIndex("PartId");

                    b.ToTable("tb_combination", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("ingredient_id");

                    b.HasIndex("ServiceId");

                    b.ToTable("tb_ingredient", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("order_id");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("tb_order", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pricehistoryingredient_id");

                    b.HasIndex("IngredientId");

                    b.ToTable("tb_pricehistoryingredient", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pricehistoryvariant_id");

                    b.HasIndex("VariantId");

                    b.ToTable("tb_pricehistoryvariant", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("service_id");

                    b.ToTable("tb_service", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ingredients")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Surpass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("variant_id");

                    b.HasIndex("ServiceId");

                    b.ToTable("tb_variant", (string)null);
                });

            modelBuilder.Entity("Kiosk.Domain.Models.VariantIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("variantingredient_id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("VariantId");

                    b.ToTable("tb_variantingredient", (string)null);
                });

            modelBuilder.Entity("CartItemIngredient", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.CartItem", null)
                        .WithMany()
                        .HasForeignKey("CartItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CartItem", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.CartItem", "Reference")
                        .WithMany("CartItems")
                        .HasForeignKey("ReferenceId");

                    b.HasOne("Kiosk.Domain.Models.Variant", "Variant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Reference");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Combination", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Variant", "Comb")
                        .WithMany("Combs")
                        .HasForeignKey("CombId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.Variant", "Part")
                        .WithMany("Parts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comb");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Ingredient", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Service", "Service")
                        .WithMany("Ingredients")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Order", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Cart", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("Kiosk.Domain.Models.Order", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryIngredient", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Ingredient", "Ingredient")
                        .WithMany("PriceHistoryIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.PriceHistoryVariant", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Variant", "Variant")
                        .WithMany("PriceHistoryVariants")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Variant", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Service", "Service")
                        .WithMany("Variants")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.VariantIngredient", b =>
                {
                    b.HasOne("Kiosk.Domain.Models.Ingredient", "Ingredient")
                        .WithMany("VariantIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Models.Variant", "Variant")
                        .WithMany("VariantIngredients")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.CartItem", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Ingredient", b =>
                {
                    b.Navigation("PriceHistoryIngredients");

                    b.Navigation("VariantIngredients");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Service", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Kiosk.Domain.Models.Variant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Combs");

                    b.Navigation("Parts");

                    b.Navigation("PriceHistoryVariants");

                    b.Navigation("VariantIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
